grid_map_topic: /r0/grid_map
grid_map_visualizations:
  - name: heatmap_grid_map
    type: flat_point_cloud
    params:
      height: 0.0
  - name: likelihood_field
    type: occupancy_grid
    params:
      layer: likelihood_field
      data_min: 0.0
      data_max: 1.0
  - name: heatmap_occ
    type: occupancy_grid
    params:
      layer: sum
      data_min: 0
      data_max: 2.7
